### ISSUE TITLE
Align Package-Version header with git tag in new release

### ISSUE THREAD

**Issue by kickingvegas** [wolray/symbol-overlay#113]
Request for an updated release that aligns the `Package-Version` header value with the git tag.

**Comment by kickingvegas** [comment]
Looks like this just got fixed with https://github.com/wolray/symbol-overlay/pull/112

**Comment by kickingvegas** [comment]
Actually, re-opening because #112 now has introduced condition where the git tag 4.2 is not aligned with the the value of ~`Package-Requires`~ `Package-Version`.

**Comment by purcell** [comment]
> now has introduced condition where the git tag 4.2 is not aligned with the the value of Package-Requires.

Huh, there's now [an installable v4.2 of the package](https://stable.melpa.org/#/symbol-overlay), so I'm not sure what issue you're encountering.

**Comment by kickingvegas** [comment]
@purcell But was the tag moved? If a user checks out the tag 4.2, they will get a version of the code where the ~`Package-Requires`~ `Package-Version` header is set to 4.1.

**Comment by purcell** [comment]
You mean `Package-Version` and not `Package-Requires`, I think? If so, that's not a big deal and shouldn't stop anyone from using the package. I'm not in favour of moving tags. When we cut a 4.3, we can make sure things line up better.

**Comment by kickingvegas** [comment]
@purcell my bad, yes `Package-Version`. Will amend. To clarify, I'm not recommending moving a tag. I would of expected that the PR #112 would of created a new tag (ideally 4.3 but that's foregone).

**Comment by purcell** [comment]
Cool, yes. Well, I've just bumped the version to 4.3 and tagged it, so everything should line up now.
