### ISSUE TITLE
symbol-overlay-temp-face should not :inherit highlight

### ISSUE THREAD

**Issue by stardiviner** [wolray/symbol-overlay#13]
Because usually the face `'region` is inherit from `highlight`.
I think should change. Because when I want to region select a string, symbol-overlay auto highlight symbol will cover my region selection.

**Comment by wolray** [comment]
The reason that I use `highlight`  is that it could automatically alter and fit in different (white and dark) color-themes. Actually this feature is provided by purcell, And normally, as far as I know, the face of highlighted symbols were always distinct from the `'region`. So maybe you could try another color-theme to see if this problem still occurs.

**Comment by stardiviner** [comment]
I see. Thanks
