### ISSUE TITLE
blacklist symbols

### ISSUE THREAD

**Issue by wbolster** [wolray/symbol-overlay#17]
hi, thanks for this package!

idea:

it would be nice if the automatic temporary overlays would support a blacklist, to avoid highlighting common symbols such as `if` and `for` in programming languages which basically cause the screen to flicker in most cases. :)

**Comment by dakra** [comment]
Maybe an option to always disable keywords?
I think every(?) mode has a keywords regex for font locking
e.g. python has `python-font-lock-keywords` which we could use.

**Comment by wbolster** [comment]
yeah, that sounds cool as a generic solution, if it can made to work!

(i'm not  familiar with the font lock internals.)

**Comment by humitos** [comment]
Thanks for this plugin, it just amazing!

This is the only thing that I'm missing from `highlight-symbol`. That plugin has a setting that I use like this to ignore some highlights:

```lisp
  (setq highlight-symbol-ignore-list
        '("False" "True" "None" "self" "def" "import" "from" "if" "else" "for"
          "while" "class" "print" "and" "not" "is" "param" "rtype" "async"
          "with" "."))
```

Hope you consider to add this. Thanks!

**Comment by wbolster** [comment]
i think a callback to determine whether a symbol should be ignored is the most generic solution. since the ignore list is likely to be dependent on the major mode (i see no other use case personally), a `defcustom` that maps `major-mode` to a function that returns `nil` or non-`nil` would be a sensible ‘dispatching mechanism’.

if you think this is a sensible approach, i can try to cook up a pr (when i find time) that implements this.

**Comment by wbolster** [comment]
i opened #18 with an unfinished implementation of the idea explained in my previous comments.

feedback welcome.

**Comment by wbolster** [comment]
#18 has been merged, improvements and additions should go into new pull requests.
