### ISSUE TITLE
Please create a release

### ISSUE THREAD

**Issue by tarsius** [wolray/symbol-overlay#19]
Please create a release tag. That would make this package available to users of Melpa Stable.

**Comment by wolray** [comment]
ok, i have added a tag in the newest commit.
thanks.

**Comment by tarsius** [comment]
Please also push it :stuck_out_tongue_winking_eye:

**Comment by tarsius** [comment]
Another ping.

**Comment by tarsius** [comment]
Thanks but what I meant was `git tag v4.1; git push --tags`.

**Comment by purcell** [comment]
Sorry, yep, I forgot to push the tag, lol. Done now.

**Comment by tarsius** [comment]
Thanks! :stuck_out_tongue_winking_eye:
