### ISSUE TITLE
Allow jumping to the first and last occurrence of a symbol

### ISSUE THREAD

**Issue by Wilfred** [wolray/symbol-overlay#28]
I've been trying symbol-overlay as an alternative to symbol-highlight, and it works really well. One feature I'm missing is the ability to go the first or last instance of a symbol in a buffer.

Would you be interested in a PR for this?

**Comment by manuel-uberti** [comment]
@wolray I tried the steps you're suggesting, but it's not as quick as having the possibility to jump straight to the first/last occurrence.

**Comment by zilongshanren** [comment]
@Wilfred 

I have made up one, hope it helps:

```
(defun symbol-overlay-switch-first ()
  (interactive)
  (let* ((symbol (symbol-overlay-get-symbol))
         (keyword (symbol-overlay-assoc symbol))
         (a-symbol (car keyword))
         (before (symbol-overlay-get-list a-symbol 'car))
         (count (length before)))
    (symbol-overlay-jump-call 'symbol-overlay-basic-jump (- count))))

(defun symbol-overlay-switch-last ()
  (interactive)
  (let* ((symbol (symbol-overlay-get-symbol))
         (keyword (symbol-overlay-assoc symbol))
         (a-symbol (car keyword))
         (after (symbol-overlay-get-list a-symbol 'cdr))
         (count (length after)))
    (symbol-overlay-jump-call 'symbol-overlay-basic-jump (- count 1))))

(define-key symbol-overlay-map (kbd "<") 'symbol-overlay-switch-first)
(define-key symbol-overlay-map (kbd ">") 'symbol-overlay-switch-last)


```

**Comment by purcell** [comment]
A few people have asked for this now, so I feel this is worth adding. Would someone like to file a pull request, perhaps based on the snippet above?

**Comment by wolray** [comment]
Commands are added as `symbol-overlay-jump-first` and `symbol-overlay-jump-last`.

See the home page.
