### ISSUE TITLE
Hide unmatched lines?

### ISSUE THREAD

**Issue by clemera** [wolray/symbol-overlay#30]
Hi, thanks for this great package! Using `iedit` and `multiple-cursor` you can toggle hiding unmatched lines which is sometimes useful to get an overview of all matches without having to navigate through the symbols. If you are interested I could try to implement it.

**Comment by purcell** [comment]
I think that's a bit tangential to `symbol-overlay` because it's very easy to implement in other ways. For example, here's what I do to address essentially the same use case: https://github.com/purcell/emacs.d/blob/master/lisp/init-ivy.el#L70-L76

**Comment by clemera** [comment]
Ah, yes! But this only works shows the symbol at point not all marked symbols for example. But I guess that's not to useful after all. Thanks!

**Comment by clemera** [comment]
The joy of Emacs :) This doesn't use `regexp-opt` because it was a bit easier to avoid it:

    (swiper (mapconcat #'identity (mapcar #'car symbol-overlay-keywords-alist) "\\|"))

**Comment by purcell** [comment]
> This doesn't use `regexp-opt` because it was a bit easier to avoid it:

Really?
```
(swiper (regexp-opt (mapcar #'car symbol-overlay-keywords-alist)))
```

**Comment by clemera** [comment]
> (swiper (regexp-opt (mapcar #'car symbol-overlay-keywords-alist)))

This does not work for me. `regex-opt` expects no regex so this adds to many backslashes around the symbol regex which have to be removed so swiper can "understand".

**Comment by purcell** [comment]
Ah yes! I'd forgotten that the alist keys could be regexes. Just ignore me... :-)
