### ISSUE TITLE
feature request: highlight multiple buffer

### ISSUE THREAD

**Issue by zilongshanren** [wolray/symbol-overlay#31]
when I opened multiple buffers side by side, it would be helpful to highlight all the symbols across these buffers.

**Comment by purcell** [comment]
That would be quite complex and is almost certainly out of scope for this package.

**Comment by dakra** [comment]
@purcell is it really that difficult?
Could you not just get a list of visible buffers with
something like `(mapcar 'window-buffer (window-list))`
and then maybe check with project.el that project
and major-mode match?

I don't have any interest in this feature myself,
just curious why this would be complex and out of scope.

**Comment by purcell** [comment]
> Could you not just get a list of visible buffers with
> something like `(mapcar 'window-buffer (window-list))`
> and then maybe check with project.el that project
> and major-mode match?

This has nothing to do with projects or major modes afaict.

The complexity this would add is:

- Have to determine visible windows in the current frame
- Couldn't toggle symbol-overlay-mode in individual buffers: it would have to be a global mode
- Have to add/remove overlays across several buffers, so overlay list can no longer be buffer-local
- Have to remove overlays when buffers become invisible in the frame in which they were added

Look at the code of `avy`, for comparison, which works like this. You'll see it's much more complex than `symbol-overlay`.

**Comment by purcell** [comment]
Going to close this one for the above reasons, sorry, but thanks for the suggestion.
