### ISSUE TITLE
[Feature Request] jump and help

### ISSUE THREAD

**Issue by seagle0128** [wolray/symbol-overlay#32]
Hi, I love this amazing package and I'm enjoying!

I have two requirements. Can you think about them?

1. Jump to the first and the last. I have the implementation for it.
```elisp
(defun symbol-overlay-switch-first ()
      (interactive)
      (let* ((symbol (symbol-overlay-get-symbol))
             (keyword (symbol-overlay-assoc symbol))
             (a-symbol (car keyword))
             (before (symbol-overlay-get-list a-symbol 'car))
             (count (length before)))
        (symbol-overlay-jump-call 'symbol-overlay-basic-jump (- count))))

(defun symbol-overlay-switch-last ()
      (interactive)
      (let* ((symbol (symbol-overlay-get-symbol))
             (keyword (symbol-overlay-assoc symbol))
             (a-symbol (car keyword))
             (after (symbol-overlay-get-list a-symbol 'cdr))
             (count (length after)))
        (symbol-overlay-jump-call 'symbol-overlay-basic-jump (- count 1))))
```
I bind to `<` and `>` in ` symbol-overlay-map`.

I can make a PR if you agree.

2. Show help for keybindings. Suggest to bind to `h`.

BTW: `doom-modeline` supports `symbol-overlay`. Refer to https://emacs-china.org/t/package-symbol-overlay-symbol/7706/18?u=seagle0128.

**Comment by purcell** [comment]
For the jumping, see #28.

I've added a help binding in 39a2ad8.

Thanks!
