### ISSUE TITLE
Highlight even when there are occurrences outside of the visible window

### ISSUE THREAD

**Issue by Wilfred** [wolray/symbol-overlay#33]
I've found it confusing that `symbol-overlay-mode` doesn't highlight the symbol if the other occurrences aren't visible.

This was a feature I loved with `highlight-symbol-mode` -- I could see if a function was used by just by putting point on it.

Is this intentional, or can it be configured? I can see a mention of this behaviour in the docstring of `symbol-overlay-maybe-put-temp`.

**Comment by Wilfred** [comment]
Perhaps this could be another value for the variable `symbol-overlay-narrow`, or a new variable? This would need to affect the behaviour of `symbol-overlay-narrow`.

**Comment by wolray** [comment]
Yes, it was intentional since it could be a little bit slow when continusly detecting occurrences in a large buffer.
But i will still add a variable to toggle this feature. Maybe next weekend.
Thanks.

**Comment by wolray** [comment]
Hey. The feature is added. Check the newest version after next melpa build.
The control variable is named as `symbol-overlay-displayed-window` and set as t by default.
