### ISSUE TITLE
Request: Highlight current symbol?

### ISSUE THREAD

**Issue by jojojames** [wolray/symbol-overlay#38]
I think the highlight-symbol is able to highlight the current symbol under point.

Would be great to have the same functionality for symbol-overlay!

Thanks.

**Comment by seagle0128** [comment]
Did you try `(symbol-overlay-mode 1)`?

**Comment by jojojames** [comment]
Yes, it won't highlight the symbol under point if it's the only symbol.

**Comment by purcell** [comment]
I'm curious about why you find this behaviour helpful in `highlight-symbol`. Could you say more please?

I've never personally noticed this behaviour being confusing, and it gives me a visual clue that there is no match for the current symbol, which is actually helpful.

You can always actively highlight the current symbol using `symbol-overlay-put`, which works regardless of the number of occurrences.

**Comment by jojojames** [comment]
> Could you say more please?

Definitely! One thing I like about the highlight is that a lot of functions/utility can/may operate on the current symbol (e.g. ag-at-point/rg-at-point/etc) so it's nice to know exactly what I'll be searching for before I do the search. (Sometimes the symbol boundaries don't line up exactly with what I'd want to search so it's nice to know beforehand.)

> and it gives me a visual clue that there is no match for the current symbol, which is actually helpful.

I think with the default for symbol-overlay, it's only if symbols are in view, right? You can change the setting I guess but those two together makes it a little awkward.

**Comment by zhouchongzxc** [comment]
这个应该需要语法分析

如果当前的是变量 就得找函数

如果当前的是函数 就得找他的返回值 及封装函数

你最好给点示例代码

**Comment by purcell** [comment]
Fixed by the merging of #67, thanks @sadboy
