### ISSUE TITLE
能和color-rg结合吗？

### ISSUE THREAD

**Issue by zhouchongzxc** [wolray/symbol-overlay#41]
让他不仅搜索当前buffer
而是其他的buffer

比如
https://github.com/manateelazycat/color-rg
得到的buffer

**Comment by zhouchongzxc** [comment]
有句话说

如果你看到有一件事情没有人做，那应该是让你去做

那就我来吧

**Comment by zhouchongzxc** [comment]
好了

**Comment by wolray** [comment]
牛逼
