### ISSUE TITLE
First word on the line is not highlighted in c++mode

### ISSUE THREAD

**Issue by Hi-Angel** [wolray/symbol-overlay#43]
## Steps to reproduce

Assuming symbol-overlay is installed:

1. execute `emacs -Q --eval "(progn (package-initialize) (c++-mode) (insert \"return return\") (symbol-overlay-mode))"` *(Emacs window should appear with scratch buffer with `return return` text)*.
3. put the caret upon a `return` word

### Expected

Both `return`s gets highlighted

### Actual

Nothing happens.

## Versions

Emacs version 27.0.50, built from git
symbol-overlay version `20190305.1643` from elpa.

***upd**: simplified steps.*

**Comment by purcell** [comment]
Isn't this just because `symbol-overlay` does not highlight language keywords? e.g. see https://github.com/wolray/symbol-overlay/blob/8b8888c8b209effe12e7c32f65124236d7722d62/symbol-overlay.el#L453

**Comment by Hi-Angel** [comment]
Hmm, okay, is there a way to completely disable it? It usually interferes with my usage as I expect to have highlighted anything I put a caret upon. The case with `return`s happens particularly often, because oftentimes when you debug, or just explore, a code, you need to see all places where a function can return. So you put a caret upon `return` word, and… nothing! :/

**Comment by purcell** [comment]
Yes, you can remove one or more entries from `symbol-overlay-ignore-functions`.

**Comment by Hi-Angel** [comment]
> Yes, you can remove one or more entries from symbol-overlay-ignore-functions.

Thanks, I confirm that doing a `(setq symbol-overlay-ignore-functions ())` fixes it.

I'll send a PR a bit later that fixes this issue by mentioning this behavior in README.
