### ISSUE TITLE
Request: support customize number of overlay symbols instead of by default 8 overlay symbols

### ISSUE THREAD

**Issue by unmem** [wolray/symbol-overlay#50]

**Comment by purcell** [comment]
Could you provide more information, please? Are you talking about more or fewer symbols? How would this work, and in what way is the current scheme not working for you?

**Comment by unmem** [comment]
# Expect
1. **Are you talking about more or fewer symbols?** 
Yes, I need more overlayed symbols.

2. **How would this work, and in what way is the current scheme not working for you?**
The current scheme is supporting overlay 8 symbols, but when I overlay a different symbol
(the 9th symbol), the 1st overlayed symbol's color was removed.

3. **Expect**
Instead of overlay 8 symbols at the same time, remove this limit or add a customizable variable which the value by default is 8.

# Example
#### Current overlayed
<img width="304" alt="Screen Shot 2019-06-17 at 10 50 29 AM" src="https://user-images.githubusercontent.com/16096559/59575414-0d398380-90ee-11e9-85cf-0d6ffa63b437.png">

#### After overlay the 9th symbols, the 1st symbol color was removed
<img width="260" alt="Screen Shot 2019-06-17 at 10 51 27 AM" src="https://user-images.githubusercontent.com/16096559/59575419-0f034700-90ee-11e9-9e37-1b61c70cf5d7.png">

**Comment by purcell** [comment]
Great, thanks for the explanation!

**Comment by purcell** [comment]
I took a look at the code, and it appears that you would already be able to define additional faces and add them to `symbol-overlay-faces` to get the effect you want. Have you tried doing that? I feel like the built-in behaviour is a good default for most people, because large numbers of different colour overlays would soon become confusing.

**Comment by unmem** [comment]
thanks, you are right, I should first view the code... sorry to wasting your time

**Comment by purcell** [comment]
No worries at all.
