### ISSUE TITLE
why not support highlight region?

### ISSUE THREAD

**Issue by paopaol** [wolray/symbol-overlay#52]
Highlight selection is also very common

**Comment by purcell** [comment]
Sorry, this isn't very clear. What do you mean?

**Comment by paopaol** [comment]
> Sorry, this isn't very clear. What do you mean?

I mean, currently symbol-overlay only supports highlight symbols, but does not support highlight regions. for example, we usually want highlights **sub-string**,but some times maybe i want highlight **sub**-string only,because i want replace **sub** to **Sub** or something else.

**Comment by purcell** [comment]
Ah, I understand - thanks for clarifying.

**Comment by paopaol** [comment]
Can this feature be supported?

**Comment by wolray** [comment]
Sorry, `symbol-overlay` will only work on "symbols", no regions, no substrings.
There are so many alternative tools, even the builtin `query-replace` could do what you asked for.

**Comment by isolet** [comment]
How can I use `query-replace` to highlight a substring?

**Comment by zw963** [comment]
In fact, if you want this feature, i think [iedit-mode](https://github.com/victorhge/iedit) do the best.

Ttough, i still create a issue to hope this package can support it too anyway.
