### ISSUE TITLE
Request: add help-echo

### ISSUE THREAD

**Issue by thanhvg** [wolray/symbol-overlay#56]
Can we also add/edit overlay's help-echo property when highlight a symbol? This would be helpful when working on new code base.
Thanks

**Comment by purcell** [comment]
What would the `help-echo` text display? Not sure this would be important enough to justify the likely disruption to things like `eldoc-mode` (often) or `flycheck-mode` (occasionally).

**Comment by thanhvg** [comment]
With `help-echo` a tooltip will show the `help-echo value when mouse hovers over the symbol. In this way I can attach my comment on the symbol. This will help me to understand new code faster. 

`help-echo or any custom overlay property would be just fine  since a function to show the property value is easy to write I think.

**Comment by purcell** [comment]
Thinking about this, you can already do this by adding a custom function to `symbol-overlay-overlay-created-functions`. You can easily modify the overlay in that function. :-)

**Comment by purcell** [comment]
(Closed because I don't think this should be a default or configurable behaviour.)
