### ISSUE TITLE
Use "Rename to:" as symbol-overlay-rename prompt

### ISSUE THREAD

**Issue by hmelman** [wolray/symbol-overlay#57]
I use `symbol-overlay-rename` infrequently and when I do it prompts me with "Rename:" and the current name of the symbol. I'm never sure if behaves like `replace-string` and I'm supposed to first enter the current name and then it will prompt me for the new name; or if I'm just supposed to enter the new name.  Adding " to" to the prompt would make this clear.

**Comment by purcell** [comment]
Thanks, yes, your issue helped me notice that I also find this slightly confusing when I use it. Done.
