### ISSUE TITLE
[Feature Request] Highlight current selection region as iedit did.

### ISSUE THREAD

**Issue by zw963** [wolray/symbol-overlay#61]
e.g. i only want to highlight the `overlay` part of the symbol `symbol-overlay-put`, so, i will set mark and highlight that region first, then run `symbol-overlay-put`, but, it still highlight entire `symbol-overlay-put` part.

![image](https://user-images.githubusercontent.com/549126/90203804-482f6800-de14-11ea-9789-5c2b6628019b.png)

Following is the same effect when use with iedit package, it works as expected.

![image](https://user-images.githubusercontent.com/549126/90203935-a4928780-de14-11ea-90a4-606d3eacd17c.png)

thank you.

**Comment by purcell** [comment]
I think this was discussed in #52.

**Comment by zw963** [comment]
Okay, if there is no plan to implement this, i will close it.
