### ISSUE TITLE
11749c3 breaks things

### ISSUE THREAD

**Issue by sthfrnth** [wolray/symbol-overlay#88]
Some problems were introduced since 11749c3.

E.g. Use ctrl-s to search a string in a file. The string cannot keep highlighted.

I do not know exactly why. Got 11749c3 only by bisecting.

**Comment by cbsirb** [comment]
The same thing breaks vertico-mode, fido-mode and, I think, any minibuffer input. The candidates are not shown until you type an empty space at the end of the input.

**Comment by seagle0128** [comment]
same issue here. Even unable to highlight words now.

**Comment by seagle0128** [comment]
Same issue here. Any update, please?

**Comment by chasecaleb** [comment]
This also breaks [smartparens](https://github.com/Fuco1/smartparens). If I type `(mess` in the `*scratch*` buffer then pause for company-mode to auto activate, I get `Error in post-command-hook (sp--pair-overlay-post-command-handler): (wrong-type-argument number-or-marker-p nil)`

**Comment by jhacksworth** [comment]
It breaks hl-line mode for me. Reverting to c439b73a5f9713bb3dce98986b589bb901e22130 fixes the problem.

**Comment by seagle0128** [comment]
It seems the latest version has already fixed the issue.

**Comment by purcell** [comment]
Thanks @seagle0128, yes, I haven't been able to reproduce this issue locally now using the steps people mentioned above.
